### ISSUE TITLE
Razorpay on ios not opening payment module

### ISSUE THREAD

**Issue by essuraj** [razorpay/react-native-razorpay#186]
RazorpayCheckout.open is not opening dialog to pay.. xcode 10.2 on react-native 0.59.5.  works fine on android. the code execution is getting stuck at open method and never leaves.. if i disconnect from internet, payment failure page is called as usual.

**Comment by Rushi271193** [comment]
Getting the same issue. Only that instead of remaining stuck the checkout method return error as follows:

Attempt to present <UINavigationController: 0x7f8c6390ae00>  on <UIViewController: 0x7f8c6341fe90> which is already presenting <RCTModalHostViewController: 0x7f8c6349b7a0>
/Users/travis/build/razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized

**Comment by essuraj** [comment]
I had a page loading modal open...before checkout.. when we removed the loading modal .. this worked

**Comment by Rushi271193** [comment]
Can you be more precise? Loading modal as in?
