### ISSUE TITLE
BIT_CODE error while archiving

### ISSUE THREAD

**Issue by rajaishwary** [razorpay/react-native-razorpay#20]
../ios/Razorpay.framework/Razorpay(RazorpayCheckoutViewController.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

using RN 0.40.0 tried with enable bitcode too but the same error.

**Comment by akshaybhalotia** [comment]
Hey @rajaishwary , are you setting bitcode enabled to `YES` in your build setting? If yes, please replace the `Razorpay.framework` file with the bitcode enabled version. This should be done at the following places.

![screen shot 2017-03-23 at 7 55 11 pm](https://cloud.githubusercontent.com/assets/9196911/24252274/feb345e4-1002-11e7-82ec-6e19360e144e.png)

The link to download bitcode enabled version of the framework is http://downloads.razorpay.com/Razorpay.framework-0.15.0-bitcode.zip

**Comment by rajaishwary** [comment]
Hi @akshaybhalotia .. Yes i have tried your suggestions but ended up disabling the BIT_CODE for the whole project.

**Comment by sagark1510** [comment]
@rajaishwary what solution did you find for this as I also got the same error, and enabling BIT_CODE for  this particular project does not work.

**Comment by iThink32** [comment]
which version of the package are you using and on which Xcode version are you doing so ?

**Comment by sagark1510** [comment]
@iThink32  2.0.4 latest version on xcode 9.3

**Comment by iThink32** [comment]
can u send a screenshot of the error that you are facing?

**Comment by iThink32** [comment]
I believe it is not a bitcode related issue , it is because you are trying to archive our framework as is , without removing the architectures added for running it on a simulator.

please follow this tutorial and add the given run script to your build phases so that the simulator architectures are removed from all your existing frameworks.Im sure it will work after that

this link explains why you are facing the error:
https://stackoverflow.com/questions/46404236/failed-to-verify-bitcode-while-exporting-archive-for-ad-hoc-distribution-tried?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

and this link has the soln:-
http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by sagark1510** [comment]
@iThink32 

Thank you very much mate. That was the real issue.
