### ISSUE TITLE
Error while Archiving Objective c app(Found an unexpected Mach-O header code: 0x72613c21)

### ISSUE THREAD

**Issue by ajith8291** [razorpay/react-native-razorpay#212]
I have implemented Razorpay SDK in my Objective C project. It works fine with development mode but throws error while arching the build. Added run script as suggested in https://razorpay.com/docs/payment-gateway/ios-integration/standard/integration-videos/

Can someone help me to solve this.

CC:@iThink32

**Comment by Nautiyalsachin** [comment]
Hi @ajith8291: please update the current SDK and also I would suggest you use cocoa pods for installing Razorpay SDK as it will eliminate the use of run script and it will be a more easier process for you.

Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a 
new issue if you have any additional queries.

**Comment by sejalthesiya** [comment]
can you please  help me to resolve this same issue

**Comment by Nautiyalsachin** [comment]
@sejalthesiya : Have you tried this with the latest react-native-razorpay 2.1.32 plugin ?
