### ISSUE TITLE
found an unexpected Mach-O header code: 0x72613c21 in Xcode 11

### ISSUE THREAD

**Issue by Coppercodes1** [razorpay/react-native-razorpay#232]
Archiving the project works well. But when I tried distributing I get the error " found an unexpected Mach-O header code: 0x72613c21 ". After googling, the solutions said I need to remove the framework from embedded frameworks. If I remove it, the disappears but the app does not work.

**Comment by tejas-freo** [comment]
I am also facing the same issue.

**Comment by Nautiyalsachin** [comment]
Please try the latest version, i.e. - 2.1.31

**Comment by tejas-freo** [comment]
I am already using the version mentioned. Any other solution please

**Comment by Coppercodes1** [comment]
Fixed it by adding the framework using cocoapods. 
Add the following line in the podfile and update pod. 
pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git',  :branch => 'swift5.1'.
Dont forget to link it.

**Comment by tejas-freo** [comment]
Is there any solution without using podfile because my project I am not using any pods

**Comment by Nautiyalsachin** [comment]
Hi @tejas-freo : You can try manual linking as mentioned in the docs, also we recommend to use AUTO LINKING. Also, try our new and updated react-native-razorpay ~> 2.1.32. 

Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.
