### ISSUE TITLE
Razorpay - Facing the issue image not loaded

### ISSUE THREAD

**Issue by SathishRonal** [razorpay/react-native-razorpay#269]
Referenced from: /Users/team/Library/Developer/CoreSimulator/Devices/FA7B164F-890A-48EC-AABC-7CCD6424199B/data/Containers/Bundle/Application/F0AEA122-EE6F-42A5-92C4-0B0949BD1F84/new.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found
xcode version :- 11.3 (11C29)
Razorpay pod version :- razorpay-pod (1.0.22)

**Comment by GorangV** [comment]
@SathishRonal Image not found is a generic error that Xcode throws when specific settings are not set while installing 3rd party SDKs. 

Please ensure that Razorpay.framework is present in both the Embedded Binaries and Linked Frameworks in your project settings. Also ensure that Always Embed Swift Libraries is set to "yes" in the project settings. Please note, this issue might also arise because of incompatibility of the Swift version with which Razorpay.framework is developed and the Swift version of your project. We highly recommend you to use the framework compiled with the required Swift language from our iOS documentation.

Hope this is fixed now?

**Comment by SathishRonal** [comment]
@GorangV  issue fixed, thanks for your response ☺️
