### ISSUE TITLE
Integrate UPI intent for Android?

### ISSUE THREAD

**Issue by gerzonc** [razorpay/react-native-razorpay#417]
Hi there, apologize for using the Bug Report template for this, but I was referring to the docs for this issue and there is nothing related to this on React Native docs so this template system was a bit unhelpful. How can I implement UPI Intent on Android? iOS has its section for it but Android doesn't

**Comment by vivekshindhe** [comment]
@gerzonc Could you please explain in a bit more detail what you're trying to achieve? You're using react-native-razorpay library and want to use UPI Intent payments on Android? Is my assumption correct?

**Comment by gerzonc** [comment]
> @gerzonc Could you please explain in a bit more detail what you're trying to achieve? You're using react-native-razorpay library and want to use UPI Intent payments on Android? Is my assumption correct?

Correct

**Comment by vivekshindhe** [comment]
@gerzonc it should work out of the box. Could you please explain what issue you're seeing?

**Comment by gerzonc** [comment]
> @gerzonc it should work out of the box. Could you please explain what issue you're seeing?

Oh okay. Since on native platforms has their docs for it I thought that you needed to do it on Android as well. But what if I want to configure which payment methods to use on them? On iOS I can add them by adding strings to `LSApplicationQueriesSchemes`, how can I do the same on Android?

**Comment by vivekshindhe** [comment]
The LSApplicationQueriesSchemes in iOS is to let the OS know that these are the applications your application may be talking with. It's not really about configuring. In android, we made it so that the SDK comes prepackaged with those app package names so all the apps that can reply to the UPI Intent URL can be used. You should see all applications in the UPI Intent block. If you want to configure which applications you want to use, i.e, display only Gpay/phonepe and Paytm, you'll need to create a config block for it in the payload that you use to call razorpay.open(). I'm attaching the link here. Please go through it once and let me know if you need more assistance on the same. 
[Config Razorpay Doc](https://razorpay.com/docs/payments/payment-gateway/web-integration/standard/configure-payment-methods)

**Comment by gerzonc** [comment]
> The LSApplicationQueriesSchemes in iOS is to let the OS know that these are the applications your application may be talking with. It's not really about configuring. In android, we made it so that the SDK comes prepackaged with those app package names so all the apps that can reply to the UPI Intent URL can be used. You should see all applications in the UPI Intent block. If you want to configure which applications you want to use, i.e, display only Gpay/phonepe and Paytm, you'll need to create a config block for it in the payload that you use to call razorpay.open(). I'm attaching the link here. Please go through it once and let me know if you need more assistance on the same.
> [Config Razorpay Doc](https://razorpay.com/docs/payments/payment-gateway/web-integration/standard/configure-payment-methods)

Alright, but one last question then: customizing the config block won't make any effect on iOS since it requires to tell in OS level which apps I have to communicate with?

**Comment by vivekshindhe** [comment]
@gerzonc ios only supports the three apps right now. Even in that case if you add a config and don't select one of those apps while adding all three to the info.plist, you'll still see apps that you have passed in the config block and not all. Closing this issue for now. Please raise another query or comment on the same. You can also raise a ticket for query and help from your Razorpay Dashboard. Thank you.

**Comment by dakshshah96** [comment]
@vivekshindhe I got UPI intent working on iOS by adding `LSApplicationQueriesSchemes` to my Expo config file. However, Android still doesn't show the UPI intent methods. The only option I have is to enter the UPI ID manually.
